#!/bin/bash
set -e

function errcho {
  >&2 echo "$@"
}

function package_for_module {
  errcho "$ module-package $1"
  package=$(./module-package $1)
  errcho "----> $package"
  echo $package
}

function dependencies_for_package {
  if [ $@ = "base" ]; then
    return
  fi

  errcho "$ extract-dependencies $@..."
  deps=$(echo $@; extract-dependencies $@)
  for dep in $deps; do
    errcho "----> $dep"
  done
  echo $deps
}

errcho "$ file-modules $1"
modules=`file-modules $1`
for module in $modules; do
  errcho "----> $module"
done
packages=`for module in $modules; do package_for_module $module; done | sort | uniq`
all_packages=`dependencies_for_package $packages`
arg_list=`for package in $all_packages; do echo "--package $package"; done | sort | uniq`
errcho "$ stack runghc $1 `echo $arg_list`"
stack runghc $1 $arg_list
