flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- cpphs-1.19.3
- haskell-src-exts-1.17.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- polyparse-1.11
- text-1.2.1.3
resolver: ghc-7.10
